
{{--Generated by the artisan tool--}}.

@component('mail::message')
# Introduction

Thank you for registering!

@component('mail::button', ['url' => 'https://laracasts.com/'])
View the the Laracast page!
@endcomponent

@component('mail::panel',['url' => 'https://facebook.com/'])

Our Awesome app! YAYYY!!!

@endcomponent


Thanks,<br>
{{ config('app.name') }}
@endcomponent
